
name: Tests 📋

on:
  push:
    branches: ["master"]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code 🛒
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install packages 📦
        run: sudo apt-get install -y valgrind

      - name: Building with cmake 🔨
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake .. -DDS_TEST=ON
          make

      - name: Running tests 📋
        run: ./build/tests/tests

      - name: Run valgrind tests 📋
        run: bash ./valgrind.sh

